-- h_region
USE StagingDB
CREATE TABLE h_region (

R_REGIONKEY INT ,
R_NAME VARCHAR(255) ,
R_COMMENT VARCHAR(255) ,

)

SELECT * FROM h_region
DROP TABLE h_region

-- h_nation
USE StagingDB
CREATE TABLE h_nation (

N_NATIONKEY INT ,
N_NAME VARCHAR(255) ,
N_REGIONKEY INT ,
N_COMMENT VARCHAR(255) ,

)
SELECT * FROM h_nation 
DROP TABLE h_nation 


-- h_supplier
USE StagingDB
CREATE TABLE h_supplier (

S_SUPPKEY INT ,
S_NAME VARCHAR(255) ,
S_ADDRESS VARCHAR(255) ,
S_NATIONKEY INT ,
S_PHONE VARCHAR(255) ,
S_ACCTBAL VARCHAR(255) ,
S_COMMENT VARCHAR(255) ,

)
SELECT * FROM h_supplier 
DROP TABLE h_supplier


-- h_customer
USE StagingDB
CREATE TABLE h_customer (

C_CUSTKEY INT ,
C_NAME VARCHAR(255) ,
C_ADDRESS VARCHAR(255) ,
C_NATIONKEY INT ,
C_PHONE VARCHAR(255) ,
C_ACCTBAL VARCHAR(255) ,
C_MKTSEGMENT VARCHAR(255) ,
C_COMMENT VARCHAR(255) ,

)
SELECT * FROM h_customer 
DROP TABLE h_customer


-- h_part
USE StagingDB
CREATE TABLE h_part (

P_PARTKEY INT ,
P_NAME VARCHAR(255) ,
P_MFGR VARCHAR(255) ,
P_BRAND VARCHAR(255) ,
P_TYPE VARCHAR(255) ,
P_SIZE INT ,
P_CONTAINER VARCHAR(255) ,
P_RETAILPRICE INT ,
P_COMMENT VARCHAR(255) ,

)
SELECT * FROM h_part 
DROP TABLE h_part


-- h_partsupp
USE StagingDB
CREATE TABLE h_partsupp (

PS_PARTKEY INT ,
PS_SUPPKEY INT ,
PS_AVAILQTY INT ,
PS_SUPPLYCOST VARCHAR(255) ,
PS_COMMENT VARCHAR(255) ,

)
SELECT * FROM h_partsupp 
DROP TABLE h_partsupp



-- h_order
USE StagingDB
CREATE TABLE h_order (

O_ORDERKEY INT ,
O_CUSTKEY INT ,
O_ORDERSTATUS VARCHAR(255) ,
O_TOTALPRICE VARCHAR(255) ,
O_ORDERDATE VARCHAR(255) ,
O_ORDERPRIORITY VARCHAR(255) ,
O_CLERK VARCHAR(255) ,
O_SHIPPRIORITY INT ,
O_COMMENT VARCHAR(255) ,

)
SELECT * FROM h_order 
DROP TABLE h_order



-- h_lineitem
USE StagingDB
CREATE TABLE h_lineitem (

L_ORDERKEY VARCHAR(255) ,
L_PARTKEY VARCHAR(255) ,
L_SUPPKEY VARCHAR(255) ,
L_LINENUMBER VARCHAR(255) ,
L_QUANTITY VARCHAR(255) ,
L_EXTENDEDPRICE VARCHAR(255) ,
L_DISCOUNT VARCHAR(255) ,
L_TAX VARCHAR(255) ,
L_RETURNFLAG VARCHAR(255) ,
L_LINESTATUS VARCHAR(255) ,
L_SHIPDATE VARCHAR(255) ,
L_COMMITDATE VARCHAR(255) ,
L_RECEIPTDATE VARCHAR(255) ,
L_SHIPINSTRUCT VARCHAR(255) ,
L_SHIPMODE VARCHAR(255) ,
L_COMMENT VARCHAR(255) ,

)
SELECT * FROM h_lineitem 
DROP TABLE h_lineitem
