a = float(input())
b = float(input())
c = float(input())
d = float(input())
e = float(input())
f = float(input())

x = ((d * e) - (f * b))/((d * a) - (b * c))
y = ((f * a) - (e * c))/((d * a) - (b * c))
print(float(x), float(y))
